platform :ios,'7.0'
target 'SEMPMobile' do
pod 'AFNetworking', '~> 3.1.0'
pod 'PNChart', '~> 0.8.9'
pod 'SDWebImage', '~>3.7.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Reachability', '~> 3.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'MLTransition', '~> 2.1.0'
pod 'IQKeyboardManager'
pod 'TZImagePickerController', '~> 1.5.0'
end
